name: Lint & Test

inputs:
  python_version:
    default: '3.x'
    type: string
  input_pkg_name:
    required: true
    type: string
  extra_packages:
    type: string

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        check-latest: true
    - name: Install Latest pip and setuptools
      run: python -m pip install -U pip setuptools wheel
      shell: bash
    - name: Install Linters
      run: |
        python -m pip install -U flake8 flake8-colors
        python -m pip install -U flake8-import-order pep8-naming
        python -m pip install -U pydocstyle pylint
      shell: bash
    - name: Install Extra Dependencies ${{ inputs.extra_packages }}
      run: python -m pip install -U ${{ inputs.extra_packages }}
      shell: bash
    - name: Run Flake8 Checks
      run: python -m flake8
      shell: bash
    - name: Run PyLint Checks on ${{ inputs.input_pkg_name }}
      run: python -m pylint -d duplicate-code ${{ inputs.input_pkg_name }}
      shell: bash
    - name: PyDocStyle
      run: python -m pydocstyle
      shell: bash
    - name: Execute Unit Tests 
      run: python -m unittest discover
      shell: bash
    - name: Check Version Updated in setup.py Before Merging
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        test -n "$(git diff -G version= origin/master HEAD -- setup.py)" || \
          exit "Package version in setup.py must be incremented before merge."wavefrontHQ/wavefront-sdk-python/austinov/rebranding/.github/actions/lint_n_test/action.yml
      shell: bash
