name: Set Global Environment Variables

on:
  workflow_call:

jobs:
  envset:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - run: echo PACKAGE_NAME="wavefront_sdk" >> $GITHUB_ENV
      - run: echo REQUIREMENTS="Deprecated requests tdigest" >> $GITHUB_ENV
      - run: echo PACKAGE_NAME is set to ${{ env.PACKAGE_NAME }}
      - run: echo REQUIREMENTS is set to ${{ env.REQUIREMENTS }}
