name: Set Global Environment Variables

on:
  workflow_call:

jobs:
  envset:
    runs-on: ubuntu-latest
    steps:
      - run: echo PACKAGE_NAME="wavefront_sdk" >> $GITHUB_ENV
        shell: bash
      - run: echo REQUIREMENTS="Deprecated requests tdigest" >> $GITHUB_ENV
        shell: bash
