name: Set Global Environment Variables

on:
  workflow_call:
    outputs:
      package_name:
        value: 'wavefront_sdk'
      requirements:
        value: 'Deprecated requests tdigest'

jobs:
  envset:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Setting outputs to:"
          echo "  package_name: ${{ outputs.package_name.value }}"
          echo "  requirements: ${{ outputs.requirements.value }}."
        shell: bash
