name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - $default-branch
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      requirements:
        type: string

jobs:
  setenv:
    uses: ./.github/workflows/env.yml
  execute:
    name: Prepare and Publish Package
    needs: setenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wavefrontHQ/wavefront-sdk-python/.github/actions/lint_n_test@master
      env:
        p_name: ${{ inputs.package_name || needs.setenv.outputs.package_name }}
        p_reqs: ${{ inputs.requirements || needs.setenv.outputs.requirements }}
      with:
        input_pkg_name: $p_name
        extra_packages: ${{ format('{0} build', $p_reqs) }}
    - name: Build Package
      run: python -m build
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
