name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - $default-branch
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      requirements:
        type: string

jobs:
  env0:
    if: ${{ github.event_name != 'workflow_call' }}
    uses: ./.github/workflows/env0.yml
  execute:
    name: Prepare and Publish Package
    needs: env0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wavefrontHQ/wavefront-sdk-python/.github/actions/lint_n_test@master
      env:
        pkg_name: ${{ inputs.package_name || needs.env0.outputs.package_name }}
        pkg_reqs: ${{ inputs.requirements || needs.env0.outputs.requirements }}
      with:
        input_pkg_name: $pkg_name
        extra_packages: ${{ format('{0} build', $pkg_reqs) }}
    - name: Build Package
      run: python -m build
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
