name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      requirements:
        type: string

jobs:
  env0:
    if: ${{ github.event_name != 'workflow_call' }}
    uses: ./.github/workflows/env0.yml
  execute:
    name: Prepare and Publish Package
    defaults:
      run:
        shell: bash
    needs: env0
    env:
      PKG_NAME: ${{ inputs.package_name || needs.env0.outputs.package_name }}
      PKG_REQS: ${{ inputs.requirements || needs.env0.outputs.requirements }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wavefrontHQ/wavefront-sdk-python/.github/actions/lint_n_test@master
      with:
        input_pkg_name: ${{ env.PKG_NAME }}
        extra_packages: ${{ env.PKG_REQS }} build
    - name: Build Package
      run: python -m build
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
