name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - $default-branch
  workflow_call:
    inputs:
      env_yml:
        default: ./.github/workflows/env.yml
        type: string

jobs:
  setenv:
    uses: ${{ inputs.env_yml }}
  execute:
    name: Prepare and Publish Package
    needs: setenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wavefrontHQ/wavefront-sdk-python/.github/actions/lint_n_test@master
      with:
        input_pkg_name: ${{ needs.setenv.outputs.package_name }}
        extra_packages: ${{ format('{0} build', needs.setenv.outputs.requirements) }}
    - name: Build Package
      run: python -m build
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
