name: Publish the Package onto PyPI

on:
  release:
    types:
    - published
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      requirements:
        type: string

jobs:
  env0:
    if: ${{ github.event_name != 'workflow_call' }}
    uses: ./.github/workflows/env0.yml
  execute:
    name: Prepare and Publish Package
    needs: env0
    env:
      PKG_NAME: ${{ inputs.package_name || needs.env0.outputs.package_name }}
      PKG_REQS: ${{ inputs.requirements || needs.env0.outputs.requirements }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wavefrontHQ/wavefront-sdk-python/.github/actions/lint_n_test@master
      with:
        input_pkg_name: ${{ env.PKG_NAME }}
        extra_packages: ${{ env.PKG_REQS }} build
    - name: Build Package
      run: python -m build
      shell: bash
    - name: Publish Package on PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
